### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by mahdiskj** [a-m-farahani/CTU#1]
hi, this package looks so great and handy. 
How can I install it on Colab? it's urgent, I'd appreciate it if you help me.

thanks

**Comment by a-m-farahani** [comment]
> hi, this package looks so great and handy.
> How can I install it on Colab? it's urgent, I'd appreciate it if you help me.
> 
> thanks

Hi, I have not published this as a package, so you cant download it to Colab.
you can simply copy reader.py and transform.py codes into a Colab Cell and just run it. After that, you can call functions and methods of CTU.

**Comment by mahdiskj** [comment]
alright,
thanks a million
